### ISSUE TITLE
Use IEC61499 language as source instead of AML

### ISSUE THREAD

**Issue by atlewee** [equinor/iec63131#11]
I belive a better language to define the library and project data for logic would be IEC61499
The AML could be generated from this definition, or actually replaced all together by IEC61499.
You still show the symbols as we are used to today in SCD, but transfer the data as IEC61499. (Ignoring the event input/outputs)
The benefit is that you have visual tools to manage library typicals, and custom function blocks, instead of AML editor witch is a lot harder to work with and visualize changes.
It works better with the larger PLC/DCS ecosystems than a custom Norsok AML do. 
And if using the textual format will make git experience a lot better.

Typical Norsok block interface implemented visually in IEC61499:
![image](https://user-images.githubusercontent.com/11732817/134517099-641e370d-e5d6-4937-83c9-25a2b751d6fe.png)

The XML representation:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<FBType Name="MB" Comment="Measure Binary">
	<Identification Standard="63131" Classification="standard norsoc function block">
	</Identification>
	<VersionInfo Organization="Equinor" Version="1.0" Author="Atle Wee Førre" Date="2021-09-23">
	</VersionInfo>
	<InterfaceList>
		<EventInputs>
			<Event Name="REQ" Type="Event" Comment="Normal Execution Request">
			</Event>
		</EventInputs>
		<EventOutputs>
			<Event Name="CNF" Type="Event" Comment="Execution Confirmation">
			</Event>
		</EventOutputs>
		<InputVars>
			<VarDeclaration Name="FB" Type="BOOL" Comment=""/>
			<VarDeclaration Name="FU" Type="BOOL" Comment=""/>
			<VarDeclaration Name="RX" Type="BOOL" Comment=""/>
			<VarDeclaration Name="X" Type="BOOL" Comment=""/>
			<VarDeclaration Name="XF" Type="BOOL" Comment=""/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="A" Type="BOOL" Comment=""/>
			<VarDeclaration Name="BB" Type="BOOL" Comment=""/>
			<VarDeclaration Name="BU" Type="BOOL" Comment=""/>
			<VarDeclaration Name="BX" Type="BOOL" Comment=""/>
			<VarDeclaration Name="W" Type="BOOL" Comment=""/>
			<VarDeclaration Name="Y" Type="BOOL" Comment=""/>
			<VarDeclaration Name="YF" Type="BOOL" Comment=""/>
		</OutputVars>
	</InterfaceList>
</FBType>

```

Code / Text representation:  (made by hand quickly)
```
FUNCTION_BLOCK MB
    EVENT_INPUT
        REQ
    END_EVENT
    EVENT_OUTPUT    
        CNF
    END_EVENT 
    VAR_INPUT
	VAR FB : BOOL
	VAR FU : BOOL
	VAR RX : BOOL
	VAR X : BOOL
	VAR XF : BOOL
    END_VAR
    VAR_OUTPUT
	VAR A : BOOL
	VAR BB : BOOL
	VAR BU : BOOL
	VAR BX : BOOL
	VAR W : BOOL
	VAR Y : BOOL
	VAR YF : BOOL
    END_VAR
END_FUNCTION_BLOCK
```

**Comment by cdenisey** [comment]
The pre-requisite for the scope of work on Krafla field project has been to work with the AML library version 0.0.7 and extend the current version to incorporate necessary elements to match current IEC standard 63131 (sequence elements attributes, and others), and not especially to redesign the entire concept to match other standards, vendor specific needs, nor drawing tools. This can of course be challenged in other arena within Equinor, but not in this Github.

AML version 0.0.7 has proven itself on Johan Sverdrup Phase 2 with KM, and also used on Johan Castberg with ABB, contributing to reduction of vendor implementation time, and removing human errors by using a machine readable format to transfer engineering inputs from EPC to SAS vendor.
