### ISSUE TITLE
Document repo guidelines in-repo

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#2]
Suggest to document some guidelines either in README.md or in CONTRIBUTE.md.
Suggestions for things to cover:
- Issue creation guidelines/rules/hints
- Branching and merging philosophies (eg, pull requests to a dev branch and final PR with squash merge to release or main branch)
- Branch policies (if supported by the GitHub organization type, eg, disallow pushing and require pull request for 'main' branch)
- Checklist for release (create an issue template for the release activity, with a release checklist)
  - Removal of irrelevant parts of AML content before releasing a version, eg, remove all writer header entries

**Comment by cdenisey** [comment]
Agreed, README.md and CONTRIBUTE.md will be used to document as suggested above.
