### ISSUE TITLE
Mismatching notation for EFB function logical "XOR", '<>' vs '≠'

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#23]
IEC PAS 63131:2017, Table B.2, defines the 'not equal to' symbol ('≠', unicode U+2260) to be used for logical "XOR".
As of version 0.0.8 the library uses '&lt;&gt;' instead.
I expect the use of two characters instead of a single will conflict with the restricted space inside the EFB 'circle', and be difficult to read correctly (for a human)?
So the symbol defined in the standard should be used?

Symbol used for XOR in the library today:
![image](https://user-images.githubusercontent.com/43793099/136524877-b6b90036-d279-467f-83cd-086ac169ecff.png)

#### Sidenote:
*Though it is not the scope of this repository to change/update the standard, I'll just mention that neither choice is among the commonly used symbols for XOR (ie, from wikipedia: ⊻, ⩒, ⩛, ⊕, ↮, and ≢ . IEC notation '=1' and programming notation '^' are also mentioned on wikipedia).*

**Comment by AlexTxen** [comment]
Changed to '≠', ref. #31
