### ISSUE TITLE
Optimize NorsokSignalClass collection from 149 terminal named classes to ~10 classes named after their characteristic features

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#3]
Having 149 different interface class definitions under ‘NorsokSignalClass’ is not necessary, unless there are 149 distinct attribute values’ combinations, creating 149 variants of signals.
My initial proposal was to reduce the signal classes from 149 to six (6), which is what is illustrated in the attached image.
But perhaps the additional attributes discussed in "AML workshop 2 - attributes" lead to some increase, to around 10 signal classes.
It should be possible to use the existing 'In', 'InOut' and 'Out' classes as super-classes even though they reside in separate branches of the XML node structure.
![image](https://user-images.githubusercontent.com/43793099/131995781-a5e10e5c-62b4-46fb-944d-34796b608754.png)

**Comment by cdenisey** [comment]
This topic to be discussed with originators of the AML Library

**Comment by ipi-equinor** [comment]
The commitee wil discuss this matter with the original architects of the AML.

**Comment by cdenisey** [comment]
Discussions have been taken in the workshop held on 21.03.2023, refer to item 1. https://github.com/equinor/iec63131/blob/2c8fa87426e072459c5afc61afd97b1ce53cd28c/MOM%20AML%20Library%200.0.11%20workshop.docx

It has been agreed to change the structure and add generic interface classes.

**Comment by AlexTxen** [comment]
Implemented in 6bbd932494c3ca590080f168cc8365f0fea19eab
Issue can be closed.

Removed all specific interface classes inherited from NorsokSignalClass/In and NorsokSignalClass/Out (e.g. 'AHH'/'ALL'):
![image](https://github.com/equinor/iec63131/assets/89920801/fee46c17-f709-4369-9c4f-bed19e2a5c93)

Added generic interface classes inherited from NorsokSignalClass/In and NorsokSignalClass/Out (e.g. 'BinaryOut')
![image](https://github.com/equinor/iec63131/assets/89920801/c95ec2ed-b580-47e5-8bcf-1adf89d98e4c)
