### ISSUE TITLE
This GitHub project should reflect release planning, it should be possible to see which issues are planned to be included (closed) in a specific release

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#32]
A common way of planning when issues will be addressed is by using the GitHub milestone feature, grouping issues by milestone named <release number>, eg, "1.0.0".
This will give a nice progress bar visualization of release progress.

See example here, under the heading "Group Issues into Milestones":
https://petabridge.com/blog/use-github-professionally/

See also:
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones

**Comment by Erik0x42** [comment]
Leveraging Milestones and Labels also serves more broadly to improve bilateral communication and understanding around issues.

**Comment by cdenisey** [comment]
Yes, Milestone for next release has been created.
