### ISSUE TITLE
Add unambiguous signal source definition behind shutdown reference triangles (when split and used in logic)

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#34]
Currently the item holds two attributes:
- Reference, eg, 'ESD1-23-4'
- Sis-notation, eg, 'E'

This is not sufficient to be machine readable and unambiguously determine whether the signal comes from the shutdown level object (LB instance) or from one of several effects (SB or other instances).
The traditional human interpretation needs to be replaced with unambiguous data.
A new attribute is needed to hold information about signal source (tag + terminal).

The following scenario needs to be supported, without manual extra work:
- There are three separate shutdown triangles on an SCD page, they all have the same reference and are visually identical
- Three different internode signals are required:
  - Y output from SB for pump A
  - Y output from SB for pump B
  - YX output from LB representing the referenced shutdown level

Affected classes:
- [ ] ReferenceClassLibrary/FromSource/SignalFromShutdownSystem
- [ ] ReferenceClassLibrary/ToDestination/SignalToShutDownSystem

**Comment by cdenisey** [comment]
Discussions have been taken in the workshop held on 21.03.2023, refer to item 8. https://github.com/equinor/iec63131/blob/2c8fa87426e072459c5afc61afd97b1ce53cd28c/MOM%20AML%20Library%200.0.11%20workshop.docx

It has been agreed to add possibility to register a tag into the shutdown reference triangles. Projects to agree if this shall be used or not.

**Comment by AlexTxen** [comment]
Implemented in 75a296990204a2f8becf8adbcad10eb7557185d6
Issue can be closed.

Added 'Tag' and 'Terminal' attributes to 'SignalToShutDownSystem' and 'SignalFromShutDownSystem' classes:
![image](https://github.com/equinor/iec63131/assets/89920801/42596cbf-bca3-4d14-ae2b-2d98b9747591)
