### ISSUE TITLE
Add support for N branches in ParallelSynchronization/AlternateBranch

### ISSUE THREAD

**Issue by CocoDico78** [equinor/iec63131#36]
In release 0.0.9 of the AML library, the schema only allows for two branches for ParallelSynchronization/AlternateBranch as shown here:

![Capture2](https://user-images.githubusercontent.com/9306993/142389373-6e7905a5-2573-473b-a5e1-e442297c3585.PNG)

But IEC63131:2017 standard allows for _N_ number of branches, as shown for example in this extract of the norm, where there are 4 branches.

![Capture](https://user-images.githubusercontent.com/9306993/142389979-78459200-eb94-4995-b498-732eabae1309.PNG)

**Comment by alexandrevandamme** [comment]
Our **Live Sequence Viewer application** uses parallel branching. We would like the AML to support those use case.
Here is a video example.
https://youtu.be/macwYboa6zU

**Comment by CocoDico78** [comment]
@cdenisey How can I clarify things for you?

**Comment by CocoDico78** [comment]
**Are branches intrinsically ordered?**

From a runtime point of view, they aren't. However, one might argue that the drawer is conveying meaning through the left-to-right ordering of the branches. Moreover, the existing AML implementation specifies `SequenceFlowOut1` and `SequenceFlowOut2` outputs, suggesting some sort of order.

**How to support more than 2 branches**

- Add more `SequenceFlowOut3`, ... `SequenceFlowOutN` dynamically as needed. This needs to be checked against AML rules.
- Transform `ParallelSynchronization` with a single port `SequenceFlowOut`, and connect all children to that port. We lose ordering but we get a dynamic number of branches.
- If we want to keep ordering, we create an intermediate class called `BranchChild`. All `BranchChild` are linked to a single `ParallelSynchronization` `SequenceFlowOut` output, and they all have their own `SequenceFlowOut` to hold their content. An `Index` attribute stores ordering.

**Comment by AlexTxen** [comment]
> Add more SequenceFlowOut3, ... SequenceFlowOutN dynamically as needed. This needs to be checked against AML rules.

According to IEC 62714-1:2018:
![image](https://user-images.githubusercontent.com/89920801/146211691-005363b4-285b-47be-89c5-484d26a76da8.png)

According to IEC 62424:2016:
![image](https://user-images.githubusercontent.com/89920801/146212309-7ee3a348-a662-4056-bb09-cb258caa253b.png)
......
......
![image](https://user-images.githubusercontent.com/89920801/146211941-3b3ec617-d573-4bf9-8d47-0e9c7eedb4cd.png)

Consequently approach with dynamic adding of additional external interfaces to instances of classes is not conflicting with AML/CAEX standards.

**Comment by CocoDico78** [comment]
Thanks for that finding. I've also checked that the CAEX engine validation indeed accepts this and does not generate errors (which is in-line with what Erik was saying and that this validation is not schema based).

This just leaves us with the ordering "issue": can we agree that branches from left-to-right should use contiguous integer numbers from 1 onwards?

Final note, could we make the AML IEC 62714 documents available on the github? If we really aim at being open, we should make an effort in providing base documentation on the norm itself.

**Comment by Erik0x42** [comment]
> Final note, could we make the AML IEC 62714 documents available on the github? If we really aim at being open, we should make an effort in providing base documentation on the norm itself.

We cannot share the IEC publications, they are available from www.iec.ch

Check out "Specifications - Whitepaper", parts 1 through 6, on automationml.org:
https://www.automationml.org/download-archive/

**Comment by Erik0x42** [comment]
> This just leaves us with the ordering "issue": can we agree that branches from left-to-right should use contiguous integer numbers from 1 onwards?

I believe encoding order with 1-based indexing as a suffix to the AML `Name` is a viable solution (given that Name has no other usage?, see below).  
A challenge is to capture and convey to tool developers such convention as an explicit and published defintion, for the benefit of anyone attempting to build IEC 63131 AML import/export functionality.  
A solution to that challenge - to convey information that we are unable to encode in the AML file - could be to add an AdditionalInformation element to the AML file, in which we insert a static reference to a document URL (eg, GitHub hosted), where this document - that we refer to - contains definitions of conventions, or best practices (or whatever we call them; recommendations, norms).

### Other usage of `Name`?

Deciding on a convention to encode order into the `Name` would have some conditions/consequences.  
The `Name` (of parallel ordered terminals) must either:

1. have a fixed and agreed stem (ie, everything except the order index number is a common static part), or
2. have any freely composed stem, of non-zero length, that does not end with a numerical character
   - This would then allow other uses for the stem part of the name (where 'stem' shall be understood to mean all parts except the index suffix)
   - written as RegEx:
     - stem pattern: `^.+[^0-9]$` (any character for one or more occurrences, followed by a non-numeric character, ie, a string that does not end with a digit)
     - whole name pattern, with index as a named capture group: `^.*[^0-9](?'index'[0-9]+)$`

**Comment by AlexTxen** [comment]
Agree, that supporting document should be created and referenced in library.

Regarding ordering issue for branches:
SequenceFlowIn1..n / SequenceFlowOut1..n interfaces can be agreed to be numbered based on graphical representation from left to right. It will cover ordering issue.

`Step` `Name`'s are supposed to be "Step identification" from sequence diagrams, e.g. S1A, S1B (this is the reason not to have attribute for "Step identification" in AML library):
![image](https://user-images.githubusercontent.com/89920801/146359977-daa66d42-721b-42b5-b668-40ae65058696.png)
This is to be also documented in supporting documentation.

**Comment by CocoDico78** [comment]
I'd rather use `SequenceFlowIn1..n / SequenceFlowOut1..n` interfaces rather than Name conventions indeed. How do we decide on that and coument it?

**Comment by cdenisey** [comment]
Question to IEC committee on how to handle supporting document to AML Library?

**Comment by Erik0x42** [comment]
> Question to IEC committee on how to handle supporting document to AML Library?

In the short term we could leverage GitHub Pages:
- make a folder named 'docs', with a file named 'index.md', and write the supporting documentation there while it evolves
- open Settings in the GitHub project, [go to Pages and enable GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) by pointing it to 'main/docs'
- I think you should then - after max 10 minutes - see the results at: https://equinor.github.io/iec63131, but maybe there is one more step I'm missing

**Comment by cdenisey** [comment]
The reply from the committee is to use the README.md to add supporting documentation to the AML Library.
The task has been given to me.
