### ISSUE TITLE
Allow ordering of Actions in a given Step

### ISSUE THREAD

**Issue by CocoDico78** [equinor/iec63131#37]
Release 0.0.9 of the AML library allows to link several `Action` to a single `Step`, but there is no information regarding ordering
![Capture](https://user-images.githubusercontent.com/9306993/142392800-df248b80-ff31-41cf-9a6f-2af4f243abd7.PNG)

which means that both of these samples would be encoded the same way in AML:
![Capture1](https://user-images.githubusercontent.com/9306993/142392903-c815c2ac-c861-4ce3-a12f-39f57b1e8e12.PNG)
![Capture2](https://user-images.githubusercontent.com/9306993/142392909-b9b3fa7d-a6dc-431a-92c9-14e4785bd2d2.PNG)

**Comment by CocoDico78** [comment]
**Do Actions have an order?**

First, we need to decide whether Actions actually have an order. From a runtime point of view, they don't. They run at the same time. From a drawing point of view, they are drawn from top to bottom and I argue that this order matters for both the drawer and the reader as it conveys visual grouping and structure.
It is not explicitly said in the standard that order doesn't matter so we might need clarification from the committee themselves.

**How can we add ordering?**

Several solutions seem to be on the table:
- Add an `Index` attribute to the `Action` class
- Encode ordering in the `Name` of the AML `InstanceElement` representing the `Action`
- Add more outputs to a `Step` (ie `Y1`, `Y2`, `YN` instead of just `Y`)
- Chain actions together (Step -> Action -> Action -> Action ... instead of Step -> Action, Step -> Action etc)
- Create an intermediate class specifically to order actions as children of steps, ie an `ActionChild` class with an `Index` attribute, an `ActionOut` port to be connected to a single `Action` and an `StepIn` port to be connected to a `Step`.
- Improve the AML standard itself to allow ordered collections of children.

Solutions should be explored based on the impact they have on existing documents and backwards compatibility, based on how they complexify the schema and how they increase the size of all documents.

**Comment by Erik0x42** [comment]
> Several solutions seem to be on the table:
>     * Add an `Index` attribute to the `Action` class
>     * Encode ordering in the `Name` of the AML `InstanceElement` representing the `Action`
>     * Add more outputs to a `Step` (ie `Y1`, `Y2`, `YN` instead of just `Y`)

To align with #36 (ie, avoid divergence in the solution space), I think we should focus on the second and third items on your list (add outputs up to `Yn` or encode order in `Name`).

**Comment by AlexTxen** [comment]
> To align with #36 (ie, avoid divergence in the solution space), I think we should focus on the second and third items on your list (add outputs up to `Yn` or encode order in `Name`).

I think, that item 2 (adding outputs Y1..Yn) should be implemented, since it will make "Step" elements more consistent with other parts of library.

If item 2 will be implemented, naming of actions will be not important to achieve ordering (item 2 is enough for this purpose) and there will be no strict need to be numbered. But since naming for "action" elements is not currently defined, I think, that documented convention to name actions in numbered way can still be relevant in order to have common naming between companies/solutions.
