### ISSUE TITLE
Size of AML library definition file causes loss of GitHub functionality

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#4]
GitHub does not support showing files of the size that the file "NorsokScdLibrary.aml" currently is (41k+ lines, 1.54MB).

If we want to gain the lost features this might be a possible solution:
- Split the definition into multiple xml files, with helper scripts to do the splitting and merging to and from the combined .aml file.

## Symptom
![image](https://user-images.githubusercontent.com/43793099/131997192-8b50dec6-e188-450a-9554-283ae7de96ef.png)
## Example of missing features
![image](https://user-images.githubusercontent.com/43793099/131997691-06e03746-f1b0-48ff-9913-3443af117a76.png)

**Comment by cdenisey** [comment]
The size has now been reduced with #22 .
