### ISSUE TITLE
Change implementation of terminal aliases 'A' and 'W' for NorsokFunctionBlockClass/MB

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#49]
The standard defines 'A' and 'W' as labels that shall be used instead of 'Y', on the output terminal (Y), when action or warning alarm shall be indicated (IEC PAS 63131:2017, section A.4.11.2.2 "I/O terminals", supplementary description on terminal code 'Y' ).
A key point here is that this is a change of letter only, not a change of terminal.
For consistency the terminal that is used in connections (InternalLink's Guid + terminal name) should always be 'Y', and ExternalInterface 'Y' on the MB instance should be the only valid choice for logic connections.

Therefore, the proposal is to remove 'A' and 'W' as terminals (remove 2x ExternalInterfaces), and instead facilitate the display/definition of 'A' or 'W' as alarm definition aliases by a new attribute on the 'Y' terminal, eg, attribute name "AlarmDefinitionAlias".
The attributes 'Priority' and 'TimeDelay' must then be moved to 'Y'.

**Comment by AlexTxen** [comment]
'SequenceFlowTimeout' on 'Step' class (sequences) currently has 'Annunciation' attribute with 'Event', 'Warning', 'Alarm' possible values. 
This attribute has quite similar purpose to what is described in this issue. 
Proposal is to add same 'Annunciation' attribute to Y output of MB block. Then mapping with SCD displayed terminal label would be:
Event -> Y
Warning -> W
Alarm -> A

**Comment by ipi-equinor** [comment]
Vi er enig i at terminal skal beholde navnet Y, mens A og W kun er for visnimngs fomål på SCD.
Vi har utelatt alarm attributter fra standarden da vi anser alarm systemet vil være en funskjonalitet utenfor funksjonsblokkene.

**Comment by AlexTxen** [comment]
AML library is to be changed accordingly.

**Comment by AlexTxen** [comment]
Implemented in cc1dc71a167ad31534e57298755e9a2997fc605f
Issue can be closed.

Removed 'A' and 'W' terminals from MB
Changed MB.Y class from 'BinaryOut' to 'BinaryOutAnnunciated'
Added 'Annunciation' atrribute to MB.Y terminal
![image](https://github.com/equinor/iec63131/assets/89920801/fd4a195a-92ac-4043-bbf2-bd86d3f0e925)
