### ISSUE TITLE
Remove attribute 'Active' from classes where it doesn't have a purpose

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#5]
The Boolean attribute “Active” – which has a purpose defined in C160-AS-J-RA-00024, Appendix A2, chapter 4.9.2 – appears to have creeped into non-terminal classes, which goes beyond the existing definition
- The extended use of this attribute should be justified and documented, or the attribute should be removed from classes where it has no defined purpose
- For clarity, the attribute name should also be reconsidered, eg, “TerminalInUse” or “TerminalActive”, and given an intuitive name, the description “Placed on SCD” (which is itself un-intuitive) could be eliminated
- Since this toggle/flag is only relevant for terminals that imply alarm/warning enabling, we should consider a leaner implementation with a separate super-class for alarming terminals, with this attribute, and remove the attribute from all non-alarming terminals
  - In which case the attribute name could be further improved, eg, “EventGenerationEnabled” or “AlarmEnabled”

See also #3

**Comment by AlexTxen** [comment]
Depending on #3

**Comment by AlexTxen** [comment]
As a part of #3 implementation in 6bbd932494c3ca590080f168cc8365f0fea19eab, 'Active' attribute was removed from interfaces (except for 'BinaryOutAnnunciated' interface class).
