### ISSUE TITLE
Change LegalValue "Substitute Value" of NorsokFunctionBlockClass attribute "InputTerminals.FallbackFunction" to "Fallback Value"

### ISSUE THREAD

**Issue by AshokaK0** [equinor/iec63131#58]
Reference is made to the fourth LegalValue (Substitute Value) of NorsokFunctionBlockClass attribute "InputTerminals.FallbackFunction".
0: Last Valid
1: Min Range
2: Max Range
3: Substitute Value
4: Current Value

If the fourth LegalValue (Substitute Value) is intended to take value from attribute "InputTerminals.FallbackValue", then it is better to change "Substitute Value" to "Fallback Value".

**Comment by AlexTxen** [comment]
It was agreed during workshop (21.06.2023) to change 'FallbackValue' to 'SubstituteValue'

**Comment by AlexTxen** [comment]
Implemented in aaa3ec2f0e674e4a40dabbe461146db5cb578f11
Issue can be closed.

Changed 'FallbackValue' attribute name to 'SubstituteValue':
![image](https://github.com/equinor/iec63131/assets/89920801/0f633f33-50a9-4c7c-979f-fdd1ccfedf68)
