### ISSUE TITLE
Remove common "Hysteresis" parameter from NorsokFunctionBlockClass CA?

### ISSUE THREAD

**Issue by AshokaK0** [equinor/iec63131#59]
Is this required now (in AML) as all alarms are provided with individual hysteresis parameters?

The CA control requirements (Algorithm, IEC63131) states "Controller deviation dead band shall be available". Does WV.Hysteresis also define controller deviation dead band?

**Comment by AlexTxen** [comment]
It was agreed during workshop (21.06.2023) to keep common hysteresis parameter.
