### ISSUE TITLE
Remove common "Hysteresis" parameter from NorsokFunctionBlockClass QA?

### ISSUE THREAD

**Issue by AshokaK0** [equinor/iec63131#62]
There is a common "Hysteresis" parameter in addition to the "Hysteresis" associated with all alarms and events in QA block.
Common "Hysteresis" could be deleted from AML if it is not used in any function.

**Comment by AlexTxen** [comment]
It was agreed during workshop (21.06.2023) to keep common hysteresis parameter on CA block. 
Should be also kept on QA block for consistency.
