### ISSUE TITLE
Update LegalValues for attribute SBC.SelectControlInAuto

### ISSUE THREAD

**Issue by AshokaK0** [equinor/iec63131#63]
Currently, the "LegalValues" for attribute "SelectControlInAuto" in NorsokFunctionBlockClass SBC are as below.
[0] BinaryInputs
[1] XREQ

Change "XREQ" to the SBE unit request number "XQ".

**Comment by AlexTxen** [comment]
Implemented in aed87ec0e27dfd1065468279aaa203448a34f237
Issue can be closed.

Changed Legal Values for attribute 'SBC.SelectControlInAuto' from
```
<RequiredValue>BinaryInputs</RequiredValue>
<RequiredValue>XREQ</RequiredValue>
```
to
```
<RequiredValue>BinaryInputs</RequiredValue>
<RequiredValue>XQ</RequiredValue>
```
