### ISSUE TITLE
Include shutdown alarm and related parameters for LB block

### ISSUE THREAD

**Issue by AshokaK0** [equinor/iec63131#64]
IEC PAS 63131 for LB block states “Shutdown level alarm shall be possible to be generated due to the primary shutdown actions (input X). If the external shutdown input (XS) is initiated the shutdown level block shall not report any alarm”. Currently LB block has only Fault and Conflict alarms. Include shutdown alarm and related parameters in the AML file.

**Comment by AlexTxen** [comment]
Implemented in 0cda1b433d1867ab1b1e6adc2d69dfbb9a1a6d8f
Issue can be closed.

Added Shutdown alarm parameters to LB block:
![image](https://github.com/equinor/iec63131/assets/89920801/c8adf75a-12a9-4000-bfa0-8e37c7c27e35)
