### ISSUE TITLE
Update LegalValues for terminal attribute detail “CommunicationType” as per IEC PAS 63131?

### ISSUE THREAD

**Issue by AshokaK0** [equinor/iec63131#68]
Reference is made to the terminal attribute detail “CommunicationType” in the AML library.
Name: CommunicationType
Description: Type of signal communication.
Value:
Data Type: xs:string
LegalValues: [0] Signal Interface
                     [1] Bus Interface

As per “Table D.7 – Instrument signals” in IEC PAS 63131, the instrument signals are represented as below.
1.	General signal, e.g. logic software signal within a node or hardwired signal from transmitter to SAS. Can also be used for bus signals and serial lines.
2.	Data communication link, i.e. bus or serial line. The signal line reflects the logic end points of the signal, and not the actual bus topology.

The existing LegalValues in the AML library could be revised for better understanding of the options and selection of instrument signal types.

**Comment by AlexTxen** [comment]
It was agreed during workshop (21.06.2023) to use 'GeneralSignal' and 'DataCommunicationLink'
