### ISSUE TITLE
Missing parameter definition (RefAttributeType) on TimerR/F TimeDelay and PulseR/F PulseLength

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#70]
These four parameters seem to have been overlooked when RefAttribyteType="AttributeTypeLib/Parameter" was applied to all parameters (fd3be3bb).

**Comment by AlexTxen** [comment]
Implemented in 098a188267f42e97b7e00cdf6fb8c702831796ac
Issue can be closed.

Added RefAttribyteType='AttributeTypeLib/Parameter' to 'TimerR/F'->'TimeDelay' and 'PulseR/F'->'PulseLength', e.g.:
![image](https://github.com/equinor/iec63131/assets/89920801/7387b16b-b337-4465-9092-1731e32ace74)
