### ISSUE TITLE
Terminals (ExternalInterfaces) on sequence page connectors are missing attribute 'Direction'

### ISSUE THREAD

**Issue by Erik0x42** [equinor/iec63131#77]
Attribute 'Direction' is missing (as of version 0.0.10) on:
- ExternalInterface 'SequenceFlowIn' on InternalElement 'SequenceOffPage'
- ExternalInterface 'SequenceFlowOut' on InternalElement 'SequenceOnPage'

Fix: add the missing AML attributes.

Additional details/context:
Out of 442 ExternalInterface elements in 'NorsokSCDLibrary.aml' 439 already have an AML attribute named 'Direction', and the three that do not - out of which two are the topic of this issue - are:
| Name | ID | RefBaseClassPath |
|--------|--------|--------|
| ConnectionPoint | 9942bd9c-c19d-44e4-a197-11b9edf264e7 | AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector |
| SequenceFlowIn | 0007f5a2-0e56-4721-85f0-ad832dcc0bf5 | InterfaceClassLibrary/NorsokSequenceFlowClass/SequenceFlowIn |
| SequenceFlowOut | fb322425-292c-423d-aefc-7202ffcc92bd | InterfaceClassLibrary/NorsokSequenceFlowClass/SequenceFlowOut |

**Comment by AlexTxen** [comment]
Implemented in 853db3dcb60a1839c6126595e7b5778db8feb05b
Issue can be closed.

Added 'Direction' attribute to interfaces of 'SequenceOffPage'/'SequenceOnPage' classes, e.g.:
![image](https://github.com/equinor/iec63131/assets/89920801/caae597e-0d71-4b9e-b52b-12bf91983606)
